### ISSUE TITLE
Nest Hello Camera excluded by default

### ISSUE THREAD

**Issue by krehman** [n0rt0nthec4t/homebridge-nest-accfactory#4]
Plugin is excluding Nest Hello device by default even though no exclusion rules are configured.

`[9/24/2024, 5:07:51 PM] [NestAccfactory] Device "Brampton - ON" ignored due to it being marked as excluded`

Same behavior exhibited in Homebridge & Docker variants.

**Comment by n0rt0nthec4t** [comment]
Is the related to alpha or latest version?

**Comment by krehman** [comment]
Latest

**Comment by n0rt0nthec4t** [comment]
testing in 0.2.0-alpha.1 for fix. Please understand the 'readme' as this version includes major breaking changes moving forward

**Comment by n0rt0nthec4t** [comment]
Fixed included in 14d1a067cfa4a8f643cd65f37a2fa323d8da7db9

**Comment by n0rt0nthec4t** [comment]
Fix include in 14d1a067cfa4a8f643cd65f37a2fa323d8da7db9
