### ISSUE TITLE
No ffmpeg binary found in "/usr/bin/ffmpeg" when installed

### ISSUE THREAD

**Issue by fdm225** [n0rt0nthec4t/homebridge-nest-accfactory#5]
When trying to stream video I get the following in the logs:

No ffmpeg binary found in "/usr/bin/ffmpeg" when installed

thing is that I have it installed in that directory

Use -h to get full help or, even better, run 'man ffmpeg'
david@time-machine:/var/lib/homebridge/node_modules/homebridge-nest-accfactory/dist$ ls /usr/bin/ffmpeg
/usr/bin/ffmpeg
david@time-machine:/var/lib/homebridge/node_modules/homebridge-nest-accfactory/dist$

**Comment by n0rt0nthec4t** [comment]
Under the plug-in configuration, have you included 'ffmpeg' at the end of the path name by any change?

**Comment by fdm225** [comment]
ahh, will try that

**Comment by n0rt0nthec4t** [comment]
There is also a lot of fixes in the latest alpha release

**Comment by fdm225** [comment]
Hmm..  ok I did that but now

![image](https://github.com/user-attachments/assets/64a6215c-9ba4-49ec-a372-9a155a9df949)

**Comment by fdm225** [comment]
Happy to test but dumb question, but how do I update to the latest alpha.

**Comment by n0rt0nthec4t** [comment]
Are you able to enable debugging in HomeBridge and then send the full output? Also, does that error occur on the Nest Doorbell or just the nest Cam? What model of Nest Cam is it?  

<img width="1414" alt="Screenshot 2024-10-02 at 6 34 50 am" src="https://github.com/user-attachments/assets/96b9b83a-cd56-41dc-87d3-83839653cd14">


The alpha version can be installed in HomeBridge via its config ui. Screenshots attached. **BUT NOTE** from v0.2.0 up there is a breaking change and how to handle this is documented in the CHANGELOG.md
<img width="756" alt="Screenshot 2024-10-02 at 6 33 17 am" src="https://github.com/user-attachments/assets/f04249e1-4f63-47ed-b662-a69d3234df58">
<img width="831" alt="Screenshot 2024-10-02 at 6 33 31 am" src="https://github.com/user-attachments/assets/3f0fa554-9bcf-4a63-8d2b-64d8cfb68261">
